### ISSUE TITLE
No rule to make target 'RcppExports.o', needed by 'rerf.so'.  Stop.

### ISSUE THREAD

**Issue by davclark** [neurodata/lumberjack#58]
I'm not sure if it's something I'm doing wrong... this is on an Ubuntu 18.04 docker image (inside gigantum). Both RcppZiggurat and RcppArmadillo are installed via the CRAN PPA (c2d4u for R 3.5). Dummies isn't in the PPA, so it's installed successfully as part of the first try at installing RerF.

I'm attempting installation via `devtools::install_github('neurodata/R-RerF')`. I'm not a super-duper R developer, but it seems like `devtools::install_local` isn't happy when I give it the path to a cloned version of the repo. It complains thus:

`Installation failed: trying to get slot "name" from an object (class "git_branch") that is not an S4 object`

**Comment by davclark** [comment]
If you want to see exactly what I did, you can have a look at this project: https://gigantum.com/tinydav/test-cran-r

It doesn't build currently - illustrating the issue.

**Comment by j1c** [comment]
Try running `devtools::install_github("neurodata/R-RerF", local=FALSE)`. I too had the same issue, and adding `local=FALSE` tag fixed the issue.

**Comment by davclark** [comment]
Thanks @j1c! that fixed it. So, perhaps this should go in the README?

**Comment by davclark** [comment]
Also - I'm wondering why this is happening, but I certainly don't know enough about building R packages to diagnose...

**Comment by MrAE** [comment]
Here's what I found in the `devtools::install` man page:
>   local: if ‘FALSE’ ‘build’s the package first: this ensures that the
          installation is completely clean, and prevents any binary
          artefacts (like ‘.o’, ‘.so’) from appearing in your local
          package directory, but is considerably slower, because every
          compile has to start from scratch.

So it would seem like when installing locally the `.o` and `.so` files cause problems?
@falkben I wonder if the `.o` and `.so` files should be ignored somehow ...

**Comment by falkben** [comment]
I believe the answer is run `Rcpp::compileAttributes()` before trying to do a local install.

This is now in our build scripts (.#build.sh and .#build_win.ps1)
