### ISSUE TITLE
rotation only if p<1000 documentation?

### ISSUE THREAD

**Issue by MrAE** [neurodata/lumberjack#62]
It's kind of arbitrary and should either be noted or set as a parameter with default?
https://github.com/neurodata/R-RerF/blob/staging/R/BuildTree.R#L143

@jovo @falkben

**Comment by jovo** [comment]
can you clarify what this is about? the title is vague.

**Comment by MrAE** [comment]
In the `BuildTree.R` code if `rotate = TRUE` then the data are rotated at each node.
p is the number of columns.

> if p > 1000 then rotate only a random subset of 1000 of the dimensions

I found the below paragraph in a comment, but it should be moved into the function documentation.

        # rotate is a boolean specifying whether or not to randomly rotate the
        # for each tree. If TRUE, then a different random rotation will be applied
        # to each bagged subsample prior to building each tree. If the number of
        # dimensions is greater than 1000, then a random subset of 1000 of the
        # dimensions will be rotated and the others will be left alone

**Comment by ttomita** [comment]
Exactly. This reference is why I made chose p <= 1000

**Comment by ttomita** [comment]
We could add an option for users to choose their own limit, but I'd say
it's low priority
